pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'jonsperiments [not needed for now]'

steps:
- script: git clone https://github.com/Jonsperiments/custom-items
  displayName: 'clone custom items'

- task: Docker@0
  displayName: 'build'
  inputs:
    imageName: '$(imageName)'
    buildArguments: BUILD_ARGS=-Icustom-items/inc.dm

- task: Docker@1
  displayName: 'registry login'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: '[not needed for now]'
    command: login

- task: Docker@1
  displayName: 'push'
  inputs:
    command: 'push'
    imageName: '$(imageName)'
